CREATE TABLE TP_OUTBOX_EVENT (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type  VARCHAR2(255) NOT NULL,
    aggregate_id    VARCHAR2(255) NOT NULL,
    event_type      VARCHAR2(255) NOT NULL,
    payload         CLOB NOT NULL,
    topic           VARCHAR2(255) NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    processed       NUMBER(1) DEFAULT 0 NOT NULL,
    processed_at    TIMESTAMP
);

CREATE INDEX IDX_OUTBOX_UNPROCESSED ON TP_OUTBOX_EVENT (processed, created_at);
